version: '3.7'

services:
  aeroalpes:
    build:
      context: .
      dockerfile: aeroalpes.Dockerfile
    container_name: aeroalpes
    hostname: aeroalpes
    depends_on:
      - db
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/aeroalpes
    networks:
      - default

  db:
    image: postgres:13
    container_name: db
    hostname: db
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=aeroalpes
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - default

networks:
  default:
    driver: bridge
