services:
  alpespartners:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: alpespartners
    hostname: alpespartners
    depends_on:
      - db
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/alpespartners
    networks:
      - default

  db:
    image: postgres:17
    container_name: db
    hostname: db
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=alpespartners
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - default

networks:
  default:
    driver: bridge
